### ISSUE TITLE
Active Record Publisher

### ISSUE THREAD

**Issue by brettallred** [mxenabled/action_subscriber#57]
@mmmries Didn't we another module that we would include in Active Record objects that would automatically publish events on created, updated, deleted?  For some reason I thought we had that in here but I guess we just put the basic publisher.  Is that something you feel we should add into this gem or do you guys just want to keep your implementation in Buttress.

**Comment by mmmries** [comment]
@brettallred we haven't found a good way to generalize that code from buttress because it includes the logic to do protobuf encoding tied together with the code to trigger the publishings.

I would like to generalize a solution that doesn't enforce any specific encoding process, but it should probably get put into the new [active_publisher](https://github.com/mxenabled/active_publisher) that we are building out right now.

**Comment by brettallred** [comment]
sounds good
